language: ruby
os: osx
env: OSX=10.12
osx_image: xcode8.1
rvm: system
cache: bundler

before_install:
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - sudo chown -R $USER "$(brew --repo)"
  - git -C "$(brew --repo)" reset --hard origin/master
  - brew update || brew update
  - rm -rf "$(brew --repo $TRAVIS_REPO_SLUG)"
  - ln -s . $(brew --repo $TRAVIS_REPO_SLUG)
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024
  - sudo gem install bundler

script:
  - brew style homebrew/bundle
  - bundle exec rake

notifications:
  email:
    on_success: never
    on_failure: always
